language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - dependencies=lowest
  - dependencies=highest
services:
  - docker
before_script:
  - if [ -n "$GIT_HUB_TOKEN" ]; then composer config -g github-oauth.github.com "$GIT_HUB_TOKEN"; fi;
  - composer install
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;
script:
  - make test
deploy:
  provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    php: '7.2'
    condition: $dependencies = highest

notifications:
  slack:
    if: branch = master
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: Y7wmqQY0fyTOyqA/P8XaDSZOEg1bj9BOuJfF3rBJcrbe70vwWMHbo5xrb1k07+lsx4B2mpa6kZYCU+NUENWqzBYnyZRYgN7qsMCeGAasaur8zyiehExQshk2LaPZM5Jw/+J3LUoXKTVxyP4GAzb0NbKdnJinuzB40TZOW5m+kZA=
